In [2]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np

In [4]:
import numpy as np 
df=np.array([2,5,4,7,12,17])
print(df)

[ 2  5  4  7 12 17]


In [7]:
import numpy as np 
df=np.array([1,2,3,4,5,6,7,8,9])
df

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
import numpy as np 
df=np.array([1,2,3,4,5,6,7,8,9])
print(type(df))
print(len(df))
print(df.all())
print(df.any())
print(df.argmax())
print(df.argmin())
print(df.base)

<class 'numpy.ndarray'>
9
True
True
8
0
None


In [24]:
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
df=np.ones(100)
df

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
import numpy as np 
df=np.zeros(100)
df

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
import numpy as np 
df=np.any(1)
df

True

In [33]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.array([45, 17, 85, 56, 93])
df

array([45, 17, 85, 56, 93])

In [35]:
import seaborn as sns 
import numpy as np 
import matplotlib.pyplot as plt 
df=np.zeros(1000)
df

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [38]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np
df=np.ones(1000)
df

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [40]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.array([1,2,3,4,5])
df

array([1, 2, 3, 4, 5])

In [43]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.zeros(40)
df

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [45]:
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np 
df=np.ones(40)
df

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [49]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.absolute(-40)
df

40

In [52]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.linspace(2,5, num=5)
df

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [54]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.linspace(8,10, num=10)
df

array([ 8.        ,  8.22222222,  8.44444444,  8.66666667,  8.88888889,
        9.11111111,  9.33333333,  9.55555556,  9.77777778, 10.        ])

In [56]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.linspace(0, 10, num=20)
df

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [58]:
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np 
df=np.linspace(0,100, num=100)
df

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [61]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np
df=np.double(2)
df

2.0

In [64]:
import seaborn as sns 
import matplotlib.pyplot as plt 
import numpy as np 
df=np.empty(0)
df

array([], dtype=float64)

In [67]:
import numpy as np 
df=np.arange(10, 20, 2)
df

array([10, 12, 14, 16, 18])

In [65]:
import numpy as np 
df=np.arange(2, 10, 2)
df

array([2, 4, 6, 8])